---
title: "Lab 8"
author: "Amy, Mandi, Marielena"
date: "11/15/2021"
output: pdf_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.width = 6.5,
                      fig.height = 8)
library(tidyverse)
library(here)
library(knitr)
```

```{r}
# Load the data

star <- read_csv(here("data", "star.csv"), show_col_types = FALSE)

```

In this lab, we will use the `tidyverse` (@tidyverse) and `here` (@here) packages. We will also use `reader` by @readr and `ggplot2` by @ggplot2, both of which load automatically with the `tidyverse` package.

```{r}
# Code Chunk for Commit 3 
star %>%
  group_by(sex, frl) %>%
  summarize(math_mean = mean(tmathss), math_sd = sd(tmathss), rdg_mean = mean(treadss), rdg_sd = sd(treadss)) %>%
    kable(col.names= c("sex", "frl", "math_mean", "math_sd", "rdg_mean", "rdg_sd"),
        digits = 2,
        booktabs = FALSE)

```

```{r}
# Code Chunk for Commit 4


```


\newpage

# References
